services:
  docs:
    container_name: mkdocs
    build: .
    environment:
      - PORT=8000
    ports:
      - "$MKDOCS_PORT:8000"
    volumes:
      - .:/docs
    command: mkdocs serve -a 0.0.0.0:8000

  filemanager:
    container_name: filemanager
    build:
      context: ../2025.1-EasyCrit-fileManager
      dockerfile: Dockerfile
    ports:
      - "$FILEMANAGER_PORT:5050"
    command: uvicorn app.main:app --host 0.0.0.0 --port 5050 --reload

  auth:
    container_name: auth
    build:
      context: ../2025.1-EasyCrit-auth
      dockerfile: Dockerfile
    ports:
      - "$AUTH_PORT:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload