services:
  docs:
    container_name: mkdocs
    build: .
    environment:
      - PORT=$MKDOCS_PORT
    ports:
      - "$MKDOCS_PORT:$MKDOCS_PORT"
    volumes:
      - .:/docs
    command: mkdocs serve -a 0.0.0.0:$MKDOCS_PORT

  auth:
    container_name: auth
    build:
      context: ../2025.1-EasyCrit-auth
      dockerfile: Dockerfile
    environment:
      - PORT=$AUTH_PORT
    ports:
      - "$AUTH_PORT:$AUTH_PORT"
    command: uvicorn app.main:app --host 0.0.0.0 --port $AUTH_PORT --reload