name: easycrit

networks:
  easy-crit:
    driver: bridge

services:
  front:
    container_name: easycrit-front
    image: easycrit
    build:
      context: ./2025.1-EasyCrit-frontend
      target: dev
      dockerfile: Dockerfile
    env_file: 
      - .env
    environment:
      - PORT=${FRONTEND_PORT}
    volumes:
      - ./2025.1-EasyCrit-frontend:/frontend
      - /frontend/node_modules
      - /frontend/next
    ports:
      - "${FRONTEND_PORT:-8000}:${FRONTEND_PORT:-8000}"

  docs:
    container_name: wiki
    build: ./2025.1-EasyCrit-docs
    environment:
      - PORT=${WIKI_PORT}
    networks:
      - easy-crit
    ports:
      - "${WIKI_PORT:-3000}:${WIKI_PORT:-3000}"
    volumes:
      - ./2025.1-EasyCrit-docs:/docs
  
  auth:
    container_name: auth
    build: ./2025.1-EasyCrit-auth
    environment:
      - PORT=${AUTH_PORT}
      - USER=${PG_USER}
      - PASSWORD=${PG_PASSWORD}
      - DB_NAME=${DB_NAME}
      - ENV=${ENV}
      - DB_PORT=${PG_PORT}
    networks:
      - easy-crit
    volumes:
      - ./2025.1-EasyCrit-auth/app:/app
    ports:
      - "${AUTH_PORT:-8001}:${AUTH_PORT:-8001}"
    depends_on:
      - postgres

  session:
    container_name: session
    build: ./2025.1-EasyCrit-sessionManager
    environment:
      - PORT=${SESSION_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - easy-crit
    volumes:
      - ./2025.1-EasyCrit-sessionManager/app:/app
    ports:
      - "${SESSION_PORT:-8002}:${SESSION_PORT:-8002}"
    depends_on:
      - redis

  files:
    container_name: files
    build: ./2025.1-EasyCrit-fileManager
    environment:
      - PORT=${FILES_PORT}
      - DATABASE_URL="postgresql://${PG_USER}:${PG_PASSWORD}@postgres:5432/"
    networks:
      - easy-crit
    volumes:
      - ./2025.1-EasyCrit-fileManager/app:/app
    ports:
      - "${FILES_PORT:-8003}:${FILES_PORT:-8003}"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: bitnami/postgresql:latest
    networks:
      - easy-crit
    restart: always
    environment:
      POSTGRESQL_USERNAME: ${PG_USER}
      POSTGRESQL_PASSWORD: ${PG_PASSWORD}
      POSTGRESQL_DATABASE: ${DB_NAME}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgData:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - easy-crit
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisData:/data

volumes:
  pgData:
  redisData:
