site_name: EasyCrit Wiki
repo_url: https://github.com/fga-eps-mds/2025.1-EasyCrit-docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
markdown_extensions:
  - attr_list
nav:
    - Home: index.md
    - Guia:
      - Guia de Contribuição: artefatos/guias/contributing.md
    - Artefatos pré sprints:
      - Lean Inception: artefatos/pre_sprints/lean_inception.md
      - Quadro de Conhecimentos: artefatos/pre_sprints/quadro_de_conhecimentos.md

