site_name: EasyCrit Wiki
repo_url: https://github.com/fga-eps-mds/2025.1-EasyCrit-docs
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo-easycrit-rounded.png
  favicon: assets/logo-easycrit-rounded.png
  features:
    - navigation.tabs
    - navigation.top
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
    - Home: index.md
    - Guias:
      - Como Contribuir: artefatos/guias/contributing.md
      - Código de conduta: artefatos/guias/code-of-conduct.md
      - Guia de identidade visual: artefatos/guias/visual-identity.md
      - Política de commits: artefatos/guias/commits-policy.md
      - Como abrir uma issue: artefatos/guias/how-to-issue.md
      - Template de documentação de sprint: artefatos/guias/template-sprints.md
      - Diagrama Entidade-Relacionamento: artefatos/guias/entity-relationship-diagram.md
    - Pré projeto:
      - Lean Inception: artefatos/pre_sprints/lean_inception.md
      - Quadro de Conhecimentos: artefatos/pre_sprints/quadro_de_conhecimentos.md
    - Planejamento:
      - Documento de arquitetura: artefatos/doc_arquitetura.md
      - Protótipo de Alta Fidelidade: artefatos/pre_sprints/prototipo-documentacao.md
      - Product Backlog: artefatos/product_backlog.md
    - Sprints:
      - Sprint 1: artefatos/sprints/sprint01.md
      - Sprint 2: artefatos/sprints/sprint02.md
      - Sprint 3: artefatos/sprints/sprint03.md
      - Sprint 4: artefatos/sprints/sprint04.md
      - Sprint 5: artefatos/sprints/sprint05.md
      - Sprint 6: artefatos/sprints/sprint06.md
      - Sprint 7: artefatos/sprints/sprint07.md
      - Sprint 8: artefatos/sprints/sprint08.md
      - Sprint 9: artefatos/sprints/sprint09.md
      - Sprint 10: artefatos/sprints/sprint10.md
      - Sprint 11: artefatos/sprints/sprint11.md
    - Releases:
      - Release R1: artefatos/releases/release1.md
      - Release RN: artefatos/releases/release2.md
    - Post Mortem: artefatos/post_mortem.md
